#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULT_KEYSTORE_PATH="$ROOT_DIR/release.keystore"
SIGNING_ENV_FILE="$ROOT_DIR/.android-signing.env"
DEFAULT_KEY_ALIAS="openwhoop-release"
DEFAULT_KEYSTORE_DNAME="CN=OpenWhoop, OU=Mobile, O=OpenWhoop, L=Unknown, S=Unknown, C=US"

usage() {
  cat <<'EOF'
Generate a local Android release keystore and save the selected signing config to:
  ./release.keystore
  ./.android-signing.env

Usage:
  bash scripts/generate-android-keystore.sh

Optional environment overrides:
  ANDROID_KEYSTORE_PATH
  ANDROID_KEY_ALIAS
  ANDROID_KEYSTORE_PASSWORD
  ANDROID_KEY_PASSWORD
  ANDROID_KEYSTORE_DNAME

Notes:
  - The keystore and signing env file are local-only and should stay out of git.
  - The signing env file stores the passwords in plain text for local builds.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Missing required command: $cmd" >&2
    exit 1
  fi
}

prompt_value() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="${3:-}"
  local current_value="${!var_name:-}"
  local answer

  if [[ -n "$current_value" ]]; then
    return 0
  fi

  if [[ ! -t 0 ]]; then
    echo "$var_name must be set when running non-interactively." >&2
    exit 1
  fi

  if [[ -n "$default_value" ]]; then
    read -r -p "$prompt_text [$default_value]: " answer
    printf -v "$var_name" '%s' "${answer:-$default_value}"
  else
    read -r -p "$prompt_text: " answer
    if [[ -z "$answer" ]]; then
      echo "$var_name cannot be empty." >&2
      exit 1
    fi
    printf -v "$var_name" '%s' "$answer"
  fi
}

prompt_secret() {
  local var_name="$1"
  local prompt_text="$2"
  local allow_empty="${3:-false}"
  local current_value="${!var_name:-}"
  local answer

  if [[ -n "$current_value" ]]; then
    return 0
  fi

  if [[ ! -t 0 ]]; then
    echo "$var_name must be set when running non-interactively." >&2
    exit 1
  fi

  read -r -s -p "$prompt_text: " answer
  echo

  if [[ -z "$answer" && "$allow_empty" != "true" ]]; then
    echo "$var_name cannot be empty." >&2
    exit 1
  fi

  printf -v "$var_name" '%s' "$answer"
}

write_signing_env() {
  mkdir -p "$(dirname "$SIGNING_ENV_FILE")"
  {
    echo "# Generated by scripts/generate-android-keystore.sh"
    echo "# This file contains local signing secrets. Do not commit it."
    printf 'export ANDROID_KEYSTORE_PATH=${ANDROID_KEYSTORE_PATH:-%q}\n' "$ANDROID_KEYSTORE_PATH"
    printf 'export ANDROID_KEY_ALIAS=${ANDROID_KEY_ALIAS:-%q}\n' "$ANDROID_KEY_ALIAS"
    printf 'export ANDROID_KEYSTORE_PASSWORD=${ANDROID_KEYSTORE_PASSWORD:-%q}\n' "$ANDROID_KEYSTORE_PASSWORD"
    printf 'export ANDROID_KEY_PASSWORD=${ANDROID_KEY_PASSWORD:-%q}\n' "$ANDROID_KEY_PASSWORD"
  } > "$SIGNING_ENV_FILE"
  chmod 600 "$SIGNING_ENV_FILE"
}

require_cmd keytool

ANDROID_KEYSTORE_PATH="${ANDROID_KEYSTORE_PATH:-$DEFAULT_KEYSTORE_PATH}"
ANDROID_KEY_ALIAS="${ANDROID_KEY_ALIAS:-}"
ANDROID_KEYSTORE_PASSWORD="${ANDROID_KEYSTORE_PASSWORD:-}"
ANDROID_KEY_PASSWORD="${ANDROID_KEY_PASSWORD:-}"
ANDROID_KEYSTORE_DNAME="${ANDROID_KEYSTORE_DNAME:-$DEFAULT_KEYSTORE_DNAME}"

prompt_value ANDROID_KEY_ALIAS "Android key alias" "$DEFAULT_KEY_ALIAS"
prompt_secret ANDROID_KEYSTORE_PASSWORD "Android keystore password"
prompt_secret ANDROID_KEY_PASSWORD "Android key password (leave empty to reuse keystore password)" true

if [[ -z "$ANDROID_KEY_PASSWORD" ]]; then
  ANDROID_KEY_PASSWORD="$ANDROID_KEYSTORE_PASSWORD"
fi

if [[ -e "$ANDROID_KEYSTORE_PATH" ]]; then
  echo "Keystore already exists at $ANDROID_KEYSTORE_PATH" >&2
  echo "Delete it first or set ANDROID_KEYSTORE_PATH to a different file." >&2
  exit 1
fi

mkdir -p "$(dirname "$ANDROID_KEYSTORE_PATH")"

keytool \
  -genkeypair \
  -v \
  -storetype PKCS12 \
  -keystore "$ANDROID_KEYSTORE_PATH" \
  -alias "$ANDROID_KEY_ALIAS" \
  -keyalg RSA \
  -keysize 2048 \
  -validity 10000 \
  -storepass "$ANDROID_KEYSTORE_PASSWORD" \
  -keypass "$ANDROID_KEY_PASSWORD" \
  -dname "$ANDROID_KEYSTORE_DNAME"

write_signing_env

echo "Created Android keystore: $ANDROID_KEYSTORE_PATH"
echo "Saved signing config: $SIGNING_ENV_FILE"
